# Generated by Django 4.1.4 on 2022-12-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0003_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
