# Generated by Django 4.1.4 on 2022-12-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0004_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='viewed',
            field=models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=1),
        ),
    ]
