# Generated by Django 4.1.4 on 2022-12-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0005_movie_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='viewed',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3),
        ),
    ]
